apiVersion: apps/v1
kind: Deployment
metadata:
  name: drupalist
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      bb: web
  template:
    metadata:
      labels:
        bb: web
    spec:
      containers:
      - name: drupalist
        image: patienceman/test-node:latest
        imagePullPolicy: Never
