---
name: Docker Build
# simplest workflow possible

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-image:
    name: Build Image
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        env:
          DOCKERHUB_USERNAME: 'patienceMan'
          DOCKERHUB_TOKEN: 'mani@123456'
        with:
          username: '$DOCKERHUB_USERNAME'
          password: '$DOCKERHUB_TOKEN'

      - name: Docker run build
        uses: docker/build-push-action@v4
        with:
          push: ${{ github.event_name != 'pull_request' }}
          tags: patienceman/drupalist:latest
