---
name: Docker Build
# simplest workflow possible

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-image:
    name: Build Image
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        env:
          SUPER_SECRET: ${{ secrets.DOCKERHUB_USERNAME }}
        run: |
          example-command "$SUPER_SECRET"

      # - name: Login to Docker Hub
        # uses: docker/login-action@v2
        # run: echo '${{ toJSON(secrets) }}'
        # shell: bash
        # with:
        #   username: ${{ secrets.DOCKERHUB_USERNAME }}
        #   password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker run build
        uses: docker/build-push-action@v4
        with:
          push: ${{ github.event_name != 'pull_request' }}
          tags: patienceman/drupalist:latest
