---
name: Build with Metadata

on:
  push:
    branches:
      - main
  pull_request:

env:
  DOCKERHUB_USERNAME: 'patienceman'
  DOCKERHUB_TOKEN: 'dckr_pat_80gxjk88Bd8_yGx6vOzuhdCJdlk'

jobs:
  build-image:
    name: Build Images
    runs-on: ubuntu-latest
    steps:

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - uses: docker/login-action@v2
      - name: Login to Docker Hub
        run: echo $DOCKERHUB_TOKEN | docker login -u $DOCKERHUB_USERNAME --password-stdin

      - name: Docker meta
        id: docker_meta
        uses: docker/metadata-action@v4
        with:
          images: patienceman/drupalist
          flavor: |
            latest=false
          tags: |
            type=raw,value=04
            type=raw,value=latest,enable=${{ endsWith(github.ref, github.event.repository.default_branch) }}
            type=ref,event=pr
            type=ref,event=branch
            type=semver,pattern={{version}}

      - name: Docker build
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64,linux/arm64,linux/arm/v7
