name: Build with BuildKit Cache

on:
  push:
    branches:
      - main
  pull_request:

env:
  DOCKERHUB_USERNAME: 'patienceman'
  DOCKERHUB_TOKEN: 'dckr_pat_80gxjk88Bd8_yGx6vOzuhdCJdlk'

jobs:
  build-image:
    name: Build Image
    runs-on: ubuntu-latest
    steps:

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - uses: docker/login-action@v2
      - name: Login to Docker Hub
        run: echo 'dckr_pat_80gxjk88Bd8_yGx6vOzuhdCJdlk'N | docker login -u patienceman --password-stdin

      - name: Docker build
        uses: docker/build-push-action@v4
        with:
          push: ${{ github.event_name != 'pull_request' }}
          tags: patienceman/drupalist:02
          cache-from: type=gha
          cache-to: type=gha,mode=max
