---
# template source: https://github.com/bretfisher/super-linter-workflow/blob/main/templates/call-super-linter.yaml
name: Lint Code Base

on:
  push:
    branches: [main]
  pull_request:

jobs:
  call-super-linter:
    name: Super-Linter
    uses: super-linter/super-linter@v5.1.1

    ### Optional settings examples

    # with:
      ### For a DevOps-focused repository. Prevents some code-language linters from running
      ### defaults to false
      # devops-only: false

      ### A regex to exclude files from linting
      ### defaults to empty
      # filter-regex-exclude: html/.*
